#!/usr/bin/env python3
"""
Review historical Step8 forecasts against realized market closes.

Usage:
  python step8_review.py --root model_artifacts --ticker ^HSI
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, Optional

import numpy as np
import pandas as pd
from pandas.tseries.offsets import BDay


def _extract_close(df: pd.DataFrame) -> pd.Series:
    if df.empty:
        return pd.Series(dtype=float)

    if isinstance(df.columns, pd.MultiIndex):
        # yfinance may return MultiIndex columns
        if "Close" in df.columns.get_level_values(0):
            close_df = df.xs("Close", axis=1, level=0)
            close = close_df.iloc[:, 0]
        else:
            return pd.Series(dtype=float)
    else:
        if "Close" not in df.columns:
            return pd.Series(dtype=float)
        close = df["Close"]

    close = pd.Series(close).dropna().astype(float)
    close.index = pd.to_datetime(close.index).tz_localize(None).normalize()
    return close


def _norm_ticker(v: str) -> str:
    return str(v).strip().upper().lstrip("^")


def _same_ticker(a: str, b: str) -> bool:
    return _norm_ticker(a) == _norm_ticker(b)


def _safe_ticker_key(ticker: str) -> str:
    return "".join(ch if ch.isalnum() else "_" for ch in str(ticker)).strip("_").lower()


def _load_close_from_local_cache(root: Path, ticker: str, start: pd.Timestamp, end: pd.Timestamp) -> pd.Series:
    """
    Fallback when yfinance is unavailable.
    Expected cache path generated by notebook cache layer:
      model_artifacts/<TICKER_DIR>/market_cache/<safe_ticker>.csv
    """
    ticker_dir = root / _norm_ticker(ticker)
    cache_path = ticker_dir / "market_cache" / f"{_safe_ticker_key(ticker)}.csv"
    if not cache_path.exists():
        return pd.Series(dtype=float)
    try:
        raw = pd.read_csv(cache_path, index_col=0, parse_dates=True)
        if "Close" not in raw.columns:
            return pd.Series(dtype=float)
        s = raw["Close"].dropna().astype(float)
        s.index = pd.to_datetime(s.index).tz_localize(None).normalize()
        s = s[(s.index >= (start - pd.Timedelta(days=7)).normalize()) & (s.index <= (end + pd.Timedelta(days=7)).normalize())]
        return s.sort_index()
    except Exception:
        return pd.Series(dtype=float)


def fetch_close_series(ticker: str, start: pd.Timestamp, end: pd.Timestamp, root: Path) -> pd.Series:
    # End date in yfinance is exclusive; extend a few days to cover holidays.
    end_exclusive = (end + pd.Timedelta(days=7)).strftime("%Y-%m-%d")
    start_str = (start - pd.Timedelta(days=7)).strftime("%Y-%m-%d")

    # Lazy import to avoid hard crash when yfinance/curl_cffi is broken.
    try:
        import yfinance as yf  # type: ignore

        df = yf.download(ticker, start=start_str, end=end_exclusive, auto_adjust=False, progress=False)
        close = _extract_close(df)
        if not close.empty:
            return close
    except Exception as exc:
        print(f"[WARN] yfinance unavailable for review ({ticker}): {exc}")

    # Fallback: local cache
    close = _load_close_from_local_cache(root=root, ticker=ticker, start=start, end=end)
    if close.empty:
        print(f"[WARN] local cache close not found for {ticker} under {root}")
    return close


def resolve_actual_date(index: pd.DatetimeIndex, target_date: pd.Timestamp) -> Optional[pd.Timestamp]:
    if target_date in index:
        return target_date

    future = index[index > target_date]
    if len(future) == 0:
        return None

    next_date = future[0]
    # Allow up to 5 calendar days offset (holiday gaps).
    if (next_date - target_date).days <= 5:
        return next_date
    return None


def review_one_csv(csv_path: Path, root: Path, ticker_filter: Optional[str] = None) -> pd.DataFrame:
    df = pd.read_csv(csv_path)
    required_cols = {
        "ticker", "t0_date", "t0_close", "horizon", "target_date",
        "bear_price", "base_price", "bull_price", "base_return_pct",
    }
    if not required_cols.issubset(set(df.columns)):
        return pd.DataFrame()

    if ticker_filter is not None:
        df = df[df["ticker"].astype(str).map(_norm_ticker) == _norm_ticker(ticker_filter)].copy()
        if df.empty:
            return pd.DataFrame()

    df["t0_date"] = pd.to_datetime(df["t0_date"]).dt.normalize()
    df["target_date"] = pd.to_datetime(df["target_date"]).dt.normalize()
    today = pd.Timestamp.now().normalize()

    ticker_from_csv = str(df["ticker"].iloc[0])
    ticker = ticker_from_csv
    if ticker_filter is not None and _same_ticker(ticker_from_csv, ticker_filter):
        ticker = ticker_filter
    close_series = fetch_close_series(
        ticker=ticker,
        start=df["t0_date"].min(),
        end=df["target_date"].max(),
        root=root,
    )
    if close_series.empty:
        return pd.DataFrame()

    # Resolve each target date to the next real trading date from market close index.
    # This avoids treating exchange holidays (e.g. 2026-05-01) as tradable dates.
    df["actual_date_used"] = df["target_date"].map(lambda d: resolve_actual_date(close_series.index, d))
    df = df.dropna(subset=["actual_date_used"]).copy()
    if df.empty:
        return pd.DataFrame()

    # only evaluate matured targets based on actual tradable date
    matured = df[df["actual_date_used"] <= today].copy()
    if matured.empty:
        return pd.DataFrame()

    rows = []
    for _, row in matured.iterrows():
        target_date = pd.to_datetime(row["target_date"]).normalize()
        actual_date = pd.to_datetime(row["actual_date_used"]).normalize()

        actual_close = float(close_series.loc[actual_date])
        t0_close = float(row["t0_close"])
        base_price = float(row["base_price"])
        base_ret = float(row["base_return_pct"])
        bear_price = float(row["bear_price"])
        bull_price = float(row["bull_price"])

        actual_return_pct = (actual_close / t0_close - 1.0) * 100.0
        pred_dir = np.sign(base_ret)
        actual_dir = np.sign(actual_return_pct)

        rows.append(
            {
                "run_dir": row.get("run_dir", str(csv_path.parent)),
                "source_csv": str(csv_path),
                "ticker": ticker,
                "horizon": int(row["horizon"]),
                "t0_date": row["t0_date"].date().isoformat(),
                "target_date": target_date.date().isoformat(),
                "actual_date_used": actual_date.date().isoformat(),
                "t0_close": t0_close,
                "actual_close": actual_close,
                "bear_price": bear_price,
                "base_price": base_price,
                "bull_price": bull_price,
                "pred_base_return_pct": base_ret,
                "actual_return_pct": actual_return_pct,
                "direction_hit": int(pred_dir == actual_dir),
                "interval_hit": int(bear_price <= actual_close <= bull_price),
                "abs_error_price": abs(actual_close - base_price),
                "abs_error_return_pct": abs(actual_return_pct - base_ret),
            }
        )

    out = pd.DataFrame(rows)
    if out.empty:
        return out

    out_path = csv_path.parent / "Step8_Forecast_Review.csv"
    out.to_csv(out_path, index=False, encoding="utf-8-sig")
    return out


def summarize(master: pd.DataFrame) -> pd.DataFrame:
    if master.empty:
        return pd.DataFrame()

    grouped = master.groupby("horizon", as_index=False).agg(
        samples=("horizon", "count"),
        direction_accuracy=("direction_hit", "mean"),
        interval_coverage=("interval_hit", "mean"),
        mae_price=("abs_error_price", "mean"),
        mae_return_pct=("abs_error_return_pct", "mean"),
    )
    grouped["direction_accuracy"] = grouped["direction_accuracy"] * 100.0
    grouped["interval_coverage"] = grouped["interval_coverage"] * 100.0
    return grouped


def build_latest_1d_daily_summary(master: pd.DataFrame) -> pd.DataFrame:
    """
    Build daily summary for the latest matured trading day (1D horizon only).
    """
    if master.empty:
        return pd.DataFrame()

    m = master.copy()
    required = {"horizon", "ticker", "actual_date_used", "direction_hit", "pred_base_return_pct", "actual_return_pct"}
    if not required.issubset(set(m.columns)):
        return pd.DataFrame()

    m = m[m["horizon"] == 1].copy()
    if m.empty:
        return pd.DataFrame()

    m["actual_date_used"] = pd.to_datetime(m["actual_date_used"], errors="coerce").dt.normalize()
    m = m.dropna(subset=["actual_date_used"])
    if m.empty:
        return pd.DataFrame()

    latest_actual_date = m["actual_date_used"].max()
    latest_df = m[m["actual_date_used"] == latest_actual_date].copy()
    if latest_df.empty:
        return pd.DataFrame()

    out = (
        latest_df.groupby("ticker", as_index=False)
        .agg(
            sample_count=("ticker", "count"),
            direction_accuracy_pct=("direction_hit", lambda s: float(np.mean(s) * 100.0)),
            pred_avg_return_pct=("pred_base_return_pct", "mean"),
            actual_avg_return_pct=("actual_return_pct", "mean"),
            latest_t0_date=("t0_date", "max"),
            latest_target_date=("target_date", "max"),
        )
    )
    out.insert(0, "actual_date_used", latest_actual_date.date().isoformat())
    return out


def _infer_ticker_from_path(path: Path) -> str:
    parts = list(path.parts)
    if "model_artifacts" in parts:
        idx = parts.index("model_artifacts")
        if idx + 1 < len(parts):
            return parts[idx + 1]
    return "UNKNOWN"


def build_step8_table_from_step6(step6_csv: Path) -> Optional[Path]:
    """
    Fallback converter:
    Step6_15D_Simulation_Prices.csv -> Step8_Forecast_Table.csv
    """
    try:
        df = pd.read_csv(step6_csv)
    except Exception:
        return None

    required = {
        "Date",
        "Deep_Bear_P06_(-1.5σ)",
        "Base_Median_P50_(0.0σ)",
        "Deep_Bull_P93_(+1.5σ)",
        "Base_Cum_Ret(%)",
    }
    if not required.issubset(df.columns):
        return None
    if df.empty:
        return None

    target_dates = pd.to_datetime(df["Date"], errors="coerce").dt.normalize()
    if target_dates.isna().all():
        return None

    base_price = pd.to_numeric(df["Base_Median_P50_(0.0σ)"], errors="coerce")
    base_ret = pd.to_numeric(df["Base_Cum_Ret(%)"], errors="coerce")
    bear_price = pd.to_numeric(df["Deep_Bear_P06_(-1.5σ)"], errors="coerce")
    bull_price = pd.to_numeric(df["Deep_Bull_P93_(+1.5σ)"], errors="coerce")

    valid0 = (~base_price.isna()) & (~base_ret.isna())
    if not valid0.any():
        return None

    first_idx = valid0.idxmax()
    denom = 1.0 + float(base_ret.iloc[first_idx]) / 100.0
    if abs(denom) < 1e-9:
        return None

    t0_close = float(base_price.iloc[first_idx]) / denom
    first_target = target_dates.iloc[first_idx]
    if pd.isna(first_target):
        return None
    t0_date = (first_target - BDay(1)).normalize()

    ticker = _infer_ticker_from_path(step6_csv)
    run_dir = step6_csv.parent
    run_date = pd.Timestamp.now().date().isoformat()
    if len(step6_csv.parts) >= 3:
        day_token = step6_csv.parts[-3]
        if len(day_token) == 8 and day_token.isdigit():
            run_date = f"{day_token[:4]}-{day_token[4:6]}-{day_token[6:]}"

    rows = []
    for td, bp, br, bearp, bullp in zip(target_dates, base_price, base_ret, bear_price, bull_price):
        if pd.isna(td) or any(pd.isna(x) for x in [bp, br, bearp, bullp]):
            continue
        horizon = int(np.busday_count(t0_date.date().isoformat(), td.date().isoformat()))
        if horizon <= 0:
            continue
        rows.append(
            {
                "run_dir": str(run_dir),
                "run_date": run_date,
                "ticker": ticker,
                "t0_date": t0_date.date().isoformat(),
                "t0_close": t0_close,
                "horizon": horizon,
                "target_date": td.date().isoformat(),
                "bear_price": float(bearp),
                "base_price": float(bp),
                "bull_price": float(bullp),
                "bear_return_pct": (float(bearp) / t0_close - 1.0) * 100.0,
                "base_return_pct": float(br),
                "bull_return_pct": (float(bullp) / t0_close - 1.0) * 100.0,
                "vol_pct": np.nan,
            }
        )

    if not rows:
        return None

    out_df = pd.DataFrame(rows)
    out_path = run_dir / "Step8_Forecast_Table.csv"
    out_df.to_csv(out_path, index=False, encoding="utf-8-sig")
    return out_path


def _extract_run_timestamp(run_dir: Path) -> int:
    """Extract numeric timestamp from run directory name (e.g., run_204313 -> 204313)."""
    name = run_dir.name
    if name.startswith("run_") and len(name) == 12:
        try:
            return int(name[4:])
        except ValueError:
            pass
    return 0


def _filter_latest_runs_per_date(csv_files: list[Path]) -> list[Path]:
    """
    Group csv_files by date extracted from path.
    For each date, keep only the latest run (largest run_YYYYMMDDHHMMSS).
    """
    from collections import defaultdict

    date_runs: Dict[str, list[Path]] = defaultdict(list)
    for f in csv_files:
        parts = f.parts
        if "model_artifacts" in parts:
            idx = parts.index("model_artifacts")
            if idx + 2 < len(parts):
                date_token = parts[idx + 2]  # e.g., 20260310
                date_runs[date_token].append(f)

    result = []
    for date, paths in sorted(date_runs.items()):
        # Find latest run by comparing run timestamp
        latest = max(paths, key=lambda p: _extract_run_timestamp(p.parent))
        result.append(latest)

    return result


def main() -> None:
    parser = argparse.ArgumentParser(description="Review Step8 forecasts.")
    parser.add_argument("--root", type=str, default="model_artifacts", help="Root artifacts folder")
    parser.add_argument("--ticker", type=str, default=None, help="Ticker filter, e.g. ^HSI")
    args = parser.parse_args()

    root = Path(args.root)
    csv_files = sorted(root.rglob("Step8_Forecast_Table.csv"))
    if not csv_files:
        generated = []
        for step6_csv in sorted(root.rglob("Step6_15D_Simulation_Prices.csv")):
            out = build_step8_table_from_step6(step6_csv)
            if out is not None:
                generated.append(out)
        if generated:
            print(f"ℹ️ Fallback generated Step8 tables: {len(generated)}")
            csv_files = sorted(root.rglob("Step8_Forecast_Table.csv"))

    if not csv_files:
        print("No Step8_Forecast_Table.csv found.")
        return

    # Filter to keep only latest run per date
    csv_files = _filter_latest_runs_per_date(csv_files)
    print(f"📊 Analyzing {len(csv_files)} latest runs (1 per date):")
    for f in csv_files:
        print(f"  - {f.parent.name}")

    all_reviews = []
    for csv_path in csv_files:
        try:
            rev = review_one_csv(csv_path, root=root, ticker_filter=args.ticker)
            if not rev.empty:
                all_reviews.append(rev)
        except Exception as exc:  # keep batch robust
            print(f"[WARN] review failed for {csv_path}: {exc}")

    if not all_reviews:
        print("No matured forecasts to review yet.")
        return

    master = pd.concat(all_reviews, ignore_index=True)
    master_path = root / "Step8_Review_Master.csv"
    master.to_csv(master_path, index=False, encoding="utf-8-sig")

    summary = summarize(master)
    summary_path = root / "Step8_Review_Summary.csv"
    summary.to_csv(summary_path, index=False, encoding="utf-8-sig")

    daily_1d = build_latest_1d_daily_summary(master)
    daily_1d_path = root / "Step8_Review_Daily_1D.csv"
    if not daily_1d.empty:
        daily_1d.to_csv(daily_1d_path, index=False, encoding="utf-8-sig")

    print(f"✅ Step8 review master saved: {master_path}")
    print(f"✅ Step8 review summary saved: {summary_path}")
    print(summary.to_string(index=False))
    if not daily_1d.empty:
        print(f"✅ Step8 latest 1D daily summary saved: {daily_1d_path}")
        print("\n📌 最近已收盘交易日（1D）方向命中摘要：")
        print(daily_1d.to_string(index=False))
    else:
        print("\nℹ️ 当前没有可用的 1D 已到期预测样本（或缺少必要字段）。")


if __name__ == "__main__":
    main()
